import { expect, test } from "@playwright/test";
import { createHmac, randomUUID } from "node:crypto";

test("phase 1 owner reports a demo bank transfer; admin requests recheck then confirms", async ({ page, browser, request, baseURL }) => {
  expect(["localhost", "127.0.0.1"]).toContain(new URL(baseURL!).hostname);
  const api = process.env.API_BASE_URL!;
  expect(["localhost", "127.0.0.1"]).toContain(new URL(api).hostname);
  const marker = `Transfer ${randomUUID()}`;
  const login = await request.post(`${api}/auth/owner/login`, { data: { email: "owner@example.com", password: "owner123" } });
  expect(login.status()).toBe(200);
  const ownerHeaders = { authorization: `Bearer ${(await login.json()).token}` };
  const petResponse = await request.post(`${api}/pets`, { headers: ownerHeaders, data: { name: marker, species: "dog" } });
  expect(petResponse.status()).toBe(201);
  const { pet } = await petResponse.json();
  const future = new Date(); future.setUTCDate(future.getUTCDate() + 9);
  const booked = await request.post(`${api}/appointments`, { headers: ownerHeaders, data: {
    petId: pet.id, type: "spa_bath", serviceName: marker, date: future.toISOString().slice(0, 10), time: "10:00",
  } });
  expect(booked.status()).toBe(201);
  const { appointment } = await booked.json();
  const staffLogin = await request.post(`${api}/auth/admin/login`, { data: { username: "admin", password: "admin123" } });
  expect(staffLogin.status()).toBe(200);
  const staffHeaders = { authorization: `Bearer ${(await staffLogin.json()).token}` };
  for (const [expectedRevision, status] of ["confirmed", "checked_in", "in_progress", "completed"].entries())
    expect((await request.patch(`${api}/appointments/${appointment.id}/status`, { headers: staffHeaders, data: { status, expectedRevision } })).status()).toBe(200);
  await page.goto("/login");
  await page.getByLabel("Email *", { exact: true }).fill("owner@example.com");
  await page.getByLabel("Password *", { exact: true }).fill("owner123");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page).toHaveURL(/\/owner\/dashboard$/);
  await page.goto("/owner/billing");
  await expect(page.getByRole("button", { name: "Thanh toán VNPay", exact: true })).toHaveCount(0);
  const checkout = page.waitForResponse(r => r.url() === `${api}/invoices/checkout` && r.request().method() === "POST");
  await page.getByRole("article").filter({ has: page.getByRole("heading", { name: marker, exact: false }) })
    .getByRole("button", { name: "Xem phí và thanh toán" }).click();
  const response = await checkout;
  expect(response.status()).toBe(200);
  const { invoice } = await response.json();
  const card = page.getByRole("article", { name: invoice.invoiceCode, exact: true });
  await card.getByRole("button", { name: "Chuyển khoản ngân hàng", exact: true }).click();
  await expect(card).toContainText("Không chuyển tiền thật");
  await expect(card).toContainText("0000000000");
  await expect(card).toContainText(invoice.transferContent);
  await card.getByLabel("Mã giao dịch ngân hàng (không bắt buộc)").fill("DEMO-BROWSER");
  await page.route(`**/api/invoices/${invoice.id}/transfer-report`, route => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: "Lỗi gửi kiểm thử" }) }));
  await card.getByRole("button", { name: "Tôi đã chuyển khoản" }).click();
  await expect(page.getByRole("alert")).toContainText("Lỗi gửi kiểm thử");
  await expect(card).not.toContainText("Đã báo chuyển khoản");
  await page.unroute(`**/api/invoices/${invoice.id}/transfer-report`);
  await card.getByRole("button", { name: "Tôi đã chuyển khoản" }).click();
  await expect(card).toContainText("Chờ cửa hàng xác nhận");
  await expect(card).toContainText("Chờ thanh toán");
  await expect(card.getByRole("button", { name: "Thanh toán tại cửa hàng" })).toBeDisabled();
  await page.reload();
  await expect(card).toContainText("Chờ cửa hàng xác nhận");
  if (process.env.BILLING_SCREENSHOT) await card.screenshot({ path: process.env.BILLING_SCREENSHOT.replace("billing.png", "manual-transfer-pending.png") });
  const adminContext = await browser.newContext({ baseURL });
  const adminPage = await adminContext.newPage();
  try {
    await adminPage.goto("/admin/login");
    await adminPage.getByLabel("Username *", { exact: true }).fill("admin");
    await adminPage.getByLabel("Password *", { exact: true }).fill("admin123");
    await adminPage.getByRole("button", { name: "Sign in as admin", exact: true }).click();
    await expect(adminPage).toHaveURL(/\/admin\/dashboard$/);
    await adminPage.goto("/admin/billing");
    const row = adminPage.getByRole("row").filter({ hasText: invoice.invoiceCode });
    await expect(row).toContainText("Khách báo đã chuyển");
    await row.getByRole("button", { name: "Chưa nhận được tiền" }).click();
    const reject = adminPage.getByRole("dialog", { name: "Chưa xác nhận chuyển khoản" });
    await reject.getByLabel("Lý do").fill("Vui lòng kiểm tra lại mã giao dịch demo");
    await reject.getByRole("button", { name: "Gửi lý do" }).click();
    await expect(reject).toHaveCount(0);
    await page.reload();
    await expect(card).toContainText("Vui lòng kiểm tra lại mã giao dịch demo");
    await card.getByLabel("Mã giao dịch ngân hàng (không bắt buộc)").fill("DEMO-CORRECTED");
    await card.getByRole("button", { name: "Tôi đã chuyển khoản" }).click();
    await expect(card).toContainText("Chờ cửa hàng xác nhận");
    await adminPage.reload();
    await row.getByRole("button", { name: "Thanh toán", exact: true }).click();
    const payment = adminPage.getByRole("dialog", { name: "Xác nhận đã thu tiền", exact: true });
    await expect(payment).toContainText("DEMO-CORRECTED");
    await expect(payment.getByLabel("Phương thức thanh toán")).toHaveValue("bank_transfer");
    await expect(payment.getByLabel("Phương thức thanh toán")).toBeDisabled();
    await payment.getByRole("button", { name: "Xác nhận đã thu đủ tiền" }).click();
    await expect(payment).toHaveCount(0);
    await expect(row).toContainText("Đã thanh toán");
    await page.reload();
    await expect(card).toContainText("Đã thanh toán");
    await expect(card).toContainText("Dữ liệu thanh toán minh họa");
    await expect(card.getByRole("button")).toHaveCount(0);
  } finally { await adminContext.close(); }
});

test("admin issues an invoice, handles payment failure and persists payment after reload", async ({ page, request, baseURL }) => {
  expect(["localhost", "127.0.0.1"]).toContain(new URL(baseURL!).hostname);
  const api = process.env.API_BASE_URL || "http://127.0.0.1:5000/api";
  expect(["localhost", "127.0.0.1"]).toContain(new URL(api).hostname);
  const marker = `Billing ${randomUUID()}`;
  const login = await request.post(`${api}/auth/owner/login`, { data: { email: "owner@example.com", password: "owner123" } });
  expect(login.status()).toBe(200);
  const ownerHeaders = { authorization: `Bearer ${(await login.json()).token}` };
  const petResult = await request.post(`${api}/pets`, { headers: ownerHeaders, data: { name: marker, species: "dog" } });
  expect(petResult.status()).toBe(201);
  const { pet } = await petResult.json();
  const future = new Date(); future.setUTCDate(future.getUTCDate() + 7);
  const appointmentResult = await request.post(`${api}/appointments`, { headers: ownerHeaders, data: {
    petId: pet.id, type: "general_checkup", serviceName: marker, date: future.toISOString().slice(0, 10), time: "10:00",
  } });
  expect(appointmentResult.status()).toBe(201);
  const { appointment } = await appointmentResult.json();
  const staffLogin = await request.post(`${api}/auth/admin/login`, { data: { username: "admin", password: "admin123" } });
  expect(staffLogin.status()).toBe(200);
  const staffHeaders = { authorization: `Bearer ${(await staffLogin.json()).token}` };
  for (const [expectedRevision, status] of ["confirmed", "checked_in", "in_progress", "completed"].entries())
    expect((await request.patch(`${api}/appointments/${appointment.id}/status`, { headers: staffHeaders, data: { status, expectedRevision } })).status()).toBe(200);

  await page.goto("/admin/login");
  await expect(page.getByText("Demo:")).toHaveCount(0);
  await page.getByLabel("Username *", { exact: true }).fill("admin");
  await page.getByLabel("Password *", { exact: true }).fill("admin123");
  await page.getByRole("button", { name: "Sign in as admin", exact: true }).click();
  await expect(page).toHaveURL(/\/admin\/dashboard$/);
  await page.goto("/admin/billing");
  await page.getByRole("button", { name: "Lập hóa đơn", exact: true }).click();
  const issue = page.getByRole("dialog", { name: "Lập hóa đơn" });
  await issue.getByLabel("Đơn cần chốt phí").selectOption(`appointment:${appointment.id}`);
  await issue.getByLabel("Đơn giá 1 (VND)").fill("250000");
  await expect(issue).toContainText(marker);
  await issue.getByRole("button", { name: "Thêm dịch vụ / phụ phí" }).click();
  await issue.getByLabel("Dịch vụ 2", { exact: true }).fill("Xét nghiệm bổ sung");
  await issue.getByLabel("Số lượng 2", { exact: true }).fill("2");
  await issue.getByLabel("Đơn giá 2 (VND)").fill("100000");
  await issue.getByLabel("Tiền thuế (VND)").fill("20000");
  await issue.getByLabel("Giảm giá (VND)").fill("10000");
  const createdResponse = page.waitForResponse(r => r.url() === `${api}/invoices` && r.request().method() === "POST");
  await issue.getByRole("button", { name: "Lưu hóa đơn", exact: true }).click();
  const created = await createdResponse;
  expect(created.status()).toBe(201);
  const { invoice } = await created.json();
  expect(invoice.totalAmount).toBe(460000);
  expect(invoice.items).toHaveLength(2);
  let row = page.getByRole("row").filter({ hasText: invoice.invoiceCode });
  await expect(row).toContainText("Chờ thanh toán");
  await expect(row).toContainText(/460\.000\s*₫/);
  await page.reload();
  row = page.getByRole("row").filter({ hasText: invoice.invoiceCode });
  await expect(row).toContainText("Chờ thanh toán");
  await row.getByRole("button", { name: "Thanh toán", exact: true }).click();
  const payment = page.getByRole("dialog", { name: "Xác nhận đã thu tiền", exact: true });
  await payment.getByLabel("Phương thức thanh toán").selectOption("bank_transfer");
  await page.route(`**/api/invoices/${invoice.id}/pay`, route => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: "Mất kết nối kiểm thử" }) }));
  await payment.getByRole("button", { name: "Xác nhận đã thu đủ tiền" }).click();
  await expect(payment.getByRole("alert")).toContainText("Mất kết nối kiểm thử");
  await expect(row).toContainText("Chờ thanh toán");
  await page.unroute(`**/api/invoices/${invoice.id}/pay`);
  await payment.getByRole("button", { name: "Xác nhận đã thu đủ tiền" }).click();
  await expect(payment).toHaveCount(0);
  await expect(row).toContainText("Đã thanh toán");
  await page.reload();
  row = page.getByRole("row").filter({ hasText: invoice.invoiceCode });
  await expect(row).toContainText("Đã thanh toán");
  await expect(row.getByRole("button", { name: "Thanh toán", exact: true })).toHaveCount(0);
  await row.getByRole("button", { name: "Xem / In", exact: true }).click();
  await expect(page.getByText("Phương thức: Chuyển khoản")).toBeVisible();
  await expect(page.getByRole("dialog", { name: "Chi tiết hóa đơn", exact: true })).not.toContainText("¥");
  if (process.env.BILLING_SCREENSHOT) {
    await page.setViewportSize({ width: 1280, height: 1100 });
    await page.screenshot({ path: process.env.BILLING_SCREENSHOT, animations: "disabled" });
  }
  await page.emulateMedia({ media: "print" });
  await expect(page.locator("#root")).toBeHidden();
  await expect(page.getByRole("dialog", { name: "Chi tiết hóa đơn", exact: true })).toBeVisible();
  await page.emulateMedia({ media: "screen" });
  const list = await request.get(`${api}/invoices`, { headers: staffHeaders });
  const stored = (await list.json()).items.find((item: { id: string }) => item.id === invoice.id);
  expect(stored.paymentStatus).toBe("paid");
  expect(stored.paymentMethod).toBe("bank_transfer");
  expect(stored.paidAt).toBeTruthy();
  expect(stored.totalAmount).toBe(460000);
});

test("owner selects onsite then VNPay; return is unpaid until signed IPN and reload", async ({ page, request, baseURL }) => {
  test.skip(process.env.VNPAY_ENABLED !== "true" || !process.env.VNPAY_HASH_SECRET || process.env.VNPAY_TMN_CODE !== "TESTCODE", "Phase 2 only: requires isolated synthetic VNPay test configuration");
  expect(["localhost", "127.0.0.1"]).toContain(new URL(baseURL!).hostname);
  const api = process.env.API_BASE_URL!;
  expect(["localhost", "127.0.0.1"]).toContain(new URL(api).hostname);
  const marker = `Online ${randomUUID()}`;
  const login = await request.post(`${api}/auth/owner/login`, { data: { email: "owner@example.com", password: "owner123" } });
  const headers = { authorization: `Bearer ${(await login.json()).token}` };
  const petResponse = await request.post(`${api}/pets`, { headers, data: { name: marker, species: "dog" } });
  expect(petResponse.status()).toBe(201);
  const { pet } = await petResponse.json();
  const future = new Date(); future.setUTCDate(future.getUTCDate() + 8);
  const created = await request.post(`${api}/appointments`, { headers, data: { petId: pet.id, type: "spa_bath", serviceName: marker, date: future.toISOString().slice(0, 10), time: "10:00" } });
  expect(created.status()).toBe(201);
  const { appointment } = await created.json();
  const admin = await request.post(`${api}/auth/admin/login`, { data: { username: "admin", password: "admin123" } });
  const staffHeaders = { authorization: `Bearer ${(await admin.json()).token}` };
  for (const [expectedRevision, status] of ["confirmed", "checked_in", "in_progress", "completed"].entries())
    expect((await request.patch(`${api}/appointments/${appointment.id}/status`, { headers: staffHeaders, data: { status, expectedRevision } })).status()).toBe(200);
  await page.goto("/login");
  await page.getByLabel("Email *", { exact: true }).fill("owner@example.com");
  await page.getByLabel("Password *", { exact: true }).fill("owner123");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page).toHaveURL(/\/owner\/dashboard$/);
  await page.goto("/owner/billing");
  const source = page.getByRole("article").filter({ has: page.getByRole("heading", { name: marker, exact: false }) });
  const checkoutResponse = page.waitForResponse(r => r.url() === `${api}/invoices/checkout` && r.request().method() === "POST");
  await source.getByRole("button", { name: "Xem phí và thanh toán" }).click();
  const checkoutResult = await checkoutResponse;
  expect(checkoutResult.status()).toBe(200);
  const { invoice } = await checkoutResult.json();
  expect(invoice.totalAmount).toBe(250000);
  const card = page.getByRole("article", { name: invoice.invoiceCode, exact: true });
  await card.getByRole("button", { name: "Thanh toán tại cửa hàng" }).click();
  await expect(card).toContainText("Hình thức: Thanh toán tại cửa hàng");
  await expect(card).toContainText("Chờ thanh toán");
  await page.reload();
  await expect(card).toContainText("Hình thức: Thanh toán tại cửa hàng");
  // Intercept the gateway navigation: never send synthetic keys or make a real payment.
  let gatewayUrl = "";
  await page.route("https://sandbox.vnpayment.vn/**", async route => {
    gatewayUrl = route.request().url();
    await route.fulfill({ status: 200, contentType: "text/html", body: "<p>Isolated gateway test</p>" });
  });
  await card.getByRole("button", { name: "Thanh toán VNPay", exact: true }).click();
  await expect(page).toHaveURL(/^https:\/\/sandbox\.vnpayment\.vn/);
  const params = new URL(gatewayUrl).searchParams;
  expect(params.get("vnp_Amount")).toBe("25000000");
  const data: Record<string, string> = { vnp_TmnCode: "TESTCODE", vnp_TxnRef: params.get("vnp_TxnRef")!, vnp_Amount: "25000000", vnp_ResponseCode: "00", vnp_TransactionStatus: "00", vnp_TransactionNo: String(Date.now()) };
  const canonical = Object.keys(data).sort().map(key => `${encodeURIComponent(key)}=${encodeURIComponent(data[key]).replace(/%20/g, "+")}`).join("&");
  const query = new URLSearchParams({ ...data, vnp_SecureHash: createHmac("sha512", process.env.VNPAY_HASH_SECRET!).update(canonical).digest("hex") }).toString();
  await page.goto(`${baseURL}/owner/billing?${query}`);
  await expect(card).toContainText("Chờ thanh toán");
  const ipn = await request.get(`${api}/payments/vnpay/ipn?${query}`);
  expect((await ipn.json()).RspCode).toBe("00");
  await page.reload();
  await expect(card).toContainText("Đã thanh toán");
  await expect(card.getByRole("button", { name: "Thanh toán VNPay", exact: true })).toHaveCount(0);
  if (process.env.BILLING_SCREENSHOT) await page.screenshot({ path: process.env.BILLING_SCREENSHOT.replace("billing.png", "owner-billing.png"), fullPage: true });
});
