import { expect, test } from "@playwright/test";
import { pagedFixture } from "./pagination-fixture";

test("directory requests pages, resets filters, and ignores a delayed earlier search", async ({ page }) => {
  const state = { currentOwnerId: "", owners: Array.from({ length: 45 }, (_, index) => ({ id: `owner-${index}`, fullName: `Khách ${String(index).padStart(2,"0")}`, phone: `09000000${String(index).padStart(2,"0")}`, petIds: [], petCount: index, loginEnabled: true })), pets: [], appointments: [], medicalRecords: [], medicalImages: [], hotelBookings: [], dailyCareNotes: [], notifications: [] };
  const requests: string[] = [];
  state.owners[40].fullName = "Khách All";
  let release: (() => void) | undefined;
  await page.addInitScript(() => sessionStorage.setItem("nipopeto_access_token", "test"));
  await page.route("**/api/**", async route => {
    const req=route.request(),url=new URL(req.url());
    if(req.method()==="OPTIONS")return route.fulfill({status:204,headers:{"access-control-allow-origin":"*","access-control-allow-headers":"*","access-control-allow-methods":"*"}});
    const json=(body: unknown)=>route.fulfill({json:body,headers:{"access-control-allow-origin":"*"}});
    if(url.pathname.endsWith("/auth/me"))return json({user:{role:"admin"}});
    if(url.pathname.endsWith("/bootstrap"))return json({...state,owners:[]});
    requests.push(req.url());
    const result=pagedFixture(req.url(),state);
    if(url.searchParams.get("q")==="slow")await new Promise<void>(resolve=>{release=resolve;});
    return json(result);
  });
  await page.goto("/admin/owners");
  await expect(page.locator("tbody tr")).toHaveCount(20);
  await expect(page.getByText("1–20 / 45 kết quả")).toBeVisible();
  await page.getByRole("button",{name:"Trang sau",exact:true}).click();
  await expect(page.getByText("Trang 2/3")).toBeVisible();
  await expect(page.locator("tbody")).toContainText("Khách 20");
  await page.getByRole("button",{name:"Trang sau",exact:true}).click();
  await expect(page.locator("tbody tr")).toHaveCount(5);
  await expect(page.getByRole("button",{name:"Trang sau",exact:true})).toBeDisabled();
  const search=page.getByLabel("Tìm khách hàng",{exact:true});
  await search.fill("Khách 44");
  await expect(page.locator("tbody tr")).toHaveCount(1);
  await expect(page.getByText("Trang 1/1")).toBeVisible();
  await search.fill("slow");
  await expect.poll(()=>Boolean(release)).toBe(true);
  await search.fill("Khách 03");
  await expect(page.locator("tbody")).toContainText("Khách 03");
  release?.();
  await expect(page.locator("tbody")).toContainText("Khách 03");
  await search.fill("all");
  await expect(page.locator("tbody tr")).toHaveCount(1);
  await expect(page.locator("tbody")).toContainText("Khách All");
  await search.fill("");
  await page.getByLabel("Số dòng mỗi trang").selectOption("50");
  await expect(page.locator("tbody tr")).toHaveCount(45);
  expect(requests.some(url=>url.includes("page=3"))).toBe(true);
  expect(requests.some(url=>url.includes("pageSize=50"))).toBe(true);
  await page.getByLabel("Số dòng mỗi trang").selectOption("20");
  await page.getByRole("button",{name:"Trang sau",exact:true}).click();
  await expect(page.getByText("Trang 2/3")).toBeVisible();
  await page.getByRole("button",{name:"Trang sau",exact:true}).click();
  await expect(page.getByText("Trang 3/3")).toBeVisible();
  state.owners.splice(20);
  await page.evaluate(() => window.dispatchEvent(new Event("focus")));
  await expect(page.getByText("Trang 1/1")).toBeVisible();
  await expect(page.locator("tbody tr")).toHaveCount(20);
});

test("owner can browse pets beyond bootstrap and their medical history uses its own page", async ({ page }) => {
  const state = { currentOwnerId:"owner",owners:[{id:"owner",fullName:"Owner",phone:"0900000000",petIds:[]}],pets:Array.from({length:25},(_,index)=>({id:`pet-${index}`,ownerId:"owner",name:`Mochi ${index}`,species:"cat",breed:"Cat",gender:"female",ageLabel:"1",healthStatus:"healthy",allergies:[],qrToken:`qr-${index}`,qrEnabled:true,publicProfile:{showOwnerPhone:true}})),appointments:[],medicalRecords:[],medicalImages:[],hotelBookings:[],dailyCareNotes:[],notifications:[] };
  await page.addInitScript(()=>sessionStorage.setItem("nipopeto_access_token","test"));
  await page.route("**/api/**",async route=>{
    const req=route.request(),path=new URL(req.url()).pathname;
    if(req.method()==="OPTIONS")return route.fulfill({status:204,headers:{"access-control-allow-origin":"*","access-control-allow-headers":"*","access-control-allow-methods":"*"}});
    const json=(body:unknown)=>route.fulfill({json:body,headers:{"access-control-allow-origin":"*"}});
    if(path.endsWith("/auth/me"))return json({user:{role:"owner"}});
    if(path.endsWith("/bootstrap"))return json({...state,pets:state.pets.slice(0,20)});
    return json(pagedFixture(req.url(),state));
  });
  await page.goto("/owner/pets");
  await expect(page.getByRole("button",{name:/Mochi 0 Cat/})).toBeVisible();
  await page.getByRole("navigation",{name:"Phân trang"}).first().getByRole("button",{name:"Trang sau",exact:true}).click();
  await expect(page.getByRole("button",{name:/Mochi 24 Cat/})).toBeVisible();
  await page.getByRole("button",{name:/Mochi 24 Cat/}).click();
  await expect(page.getByRole("heading",{name:/Mochi 24/}).first()).toBeVisible();
  await page.goto("/owner/medical-records?petId=pet-24");
  await expect(page.getByRole("heading",{name:/Mochi 24/})).toBeVisible();
  await page.getByLabel("Chọn thú cưng",{exact:true}).selectOption("pet-0");
  await expect(page.getByRole("heading",{name:/Mochi 0/})).toBeVisible();
});
