import { expect, test } from "@playwright/test";
import { randomUUID } from "node:crypto";

test("owner sees local VietQR, handles QR errors and reports payment; admin finds transfer code", async ({ page, request, browser, baseURL }) => {
  test.skip(process.env.BANK_TRANSFER_DEMO !== "false" || process.env.BANK_TRANSFER_ACCOUNT_NUMBER !== "123456789", "Use isolated fake receiving account");
  expect(["localhost", "127.0.0.1"]).toContain(new URL(baseURL!).hostname);
  const api = process.env.API_BASE_URL!;
  expect(["localhost", "127.0.0.1"]).toContain(new URL(api).hostname);
  const login = await request.post(`${api}/auth/owner/login`, { data: { email: "owner@example.com", password: "owner123" } });
  expect(login.status()).toBe(200);
  const ownerToken = (await login.json()).token;
  const headers = { authorization: `Bearer ${ownerToken}` };
  const petResult = await request.post(`${api}/pets`, { headers, data: { name: `QR ${randomUUID()}`, species: "dog" } });
  expect(petResult.status()).toBe(201);
  const { pet } = await petResult.json();
  const future = new Date(); future.setUTCDate(future.getUTCDate() + 10);
  const booking = await request.post(`${api}/appointments`, { headers, data: { petId: pet.id, type: "spa_bath", serviceName: "VietQR browser test",
    date: future.toISOString().slice(0, 10), time: "10:00" } });
  expect(booking.status()).toBe(201);
  const { appointment } = await booking.json();
  const adminLogin = await request.post(`${api}/auth/admin/login`, { data: { username: "admin", password: "admin123" } });
  expect(adminLogin.status()).toBe(200);
  const adminToken = (await adminLogin.json()).token;
  const adminHeaders = { authorization: `Bearer ${adminToken}` };
  for (const [expectedRevision, status] of ["confirmed", "checked_in", "in_progress", "completed"].entries())
    expect((await request.patch(`${api}/appointments/${appointment.id}/status`, { headers: adminHeaders, data: { status, expectedRevision } })).status()).toBe(200);
  const checkout = await request.post(`${api}/invoices/checkout`, { headers, data: { type: "appointment", relatedId: appointment.id } });
  expect(checkout.status()).toBe(200);
  const { invoice } = await checkout.json();
  await page.addInitScript(token => sessionStorage.setItem("nipopeto_access_token", token), ownerToken);
  await page.goto("/owner/billing");
  const card = page.getByRole("article", { name: invoice.invoiceCode, exact: true });
  await page.route(`**/api/invoices/${invoice.id}/transfer-qr`, route => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: "QR test failure" }) }));
  await card.getByRole("button", { name: "Chuyển khoản ngân hàng", exact: true }).click();
  await expect(card).toContainText("Chưa tải được QR");
  await expect(card).toContainText("123456789");
  await expect(card).toContainText(invoice.transferContent);
  await page.unroute(`**/api/invoices/${invoice.id}/transfer-qr`);
  await card.getByRole("button", { name: "Tải lại QR" }).click();
  const img = card.getByRole("img", { name: `VietQR thanh toán ${invoice.transferContent}` });
  await expect(img).toBeVisible();
  await expect(img).toHaveAttribute("src", /^data:image\/png;base64,/);
  await expect.poll(() => img.evaluate((el: HTMLImageElement) => el.naturalWidth)).toBe(320);
  const downloadEvent = page.waitForEvent("download");
  await card.getByRole("link", { name: "Tải mã QR" }).click();
  expect((await downloadEvent).suggestedFilename()).toBe(`${invoice.transferContent}.png`);
  await page.reload();
  await expect(img).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(img).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await img.evaluate(el => el.scrollIntoView({ block: "center" }));
  const bounds = await img.boundingBox();
  expect(bounds!.y).toBeGreaterThanOrEqual(56);
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(780);
  if (process.env.BILLING_SCREENSHOT) await page.screenshot({ path: process.env.BILLING_SCREENSHOT.replace("billing.png", "vietqr-mobile.png") });
  await card.getByRole("button", { name: "Tôi đã chuyển khoản" }).click();
  await expect(card).toContainText("Chờ cửa hàng xác nhận");
  await expect(img).toHaveCount(0);
  await expect(card).toContainText("Chờ thanh toán");
  const context = await browser.newContext({ baseURL });
  try {
    const admin = await context.newPage();
    await admin.addInitScript(token => sessionStorage.setItem("nipopeto_access_token", token), adminToken);
    await admin.goto("/admin/billing");
    await admin.getByPlaceholder("Tìm mã hóa đơn / chuyển khoản, chủ nuôi, thú cưng...").fill(invoice.transferContent);
    const row = admin.getByRole("row").filter({ hasText: invoice.invoiceCode });
    await expect(row).toBeVisible();
    await expect(admin.locator("tbody tr")).toHaveCount(1);
    await row.getByRole("button", { name: "Thanh toán", exact: true }).click();
    const dialog = admin.getByRole("dialog", { name: "Xác nhận đã thu tiền", exact: true });
    await expect(dialog).toContainText(invoice.transferContent);
    await expect(dialog).toContainText("123456789");
    await dialog.getByRole("button", { name: "Xác nhận đã thu đủ tiền" }).click();
    await expect(dialog).toHaveCount(0);
    await page.reload();
    await expect(card).toContainText("Đã thanh toán");
    await expect(img).toHaveCount(0);
  } finally { await context.close(); }
});
