import type { Actor } from "../../domain/auth.js";
import { BusinessError } from "../../domain/error.js";
import { booleanValue, enumValue, objectInput, optionalText, positiveNumber, requiredText } from "../../domain/validation.js";
import type { PetChanges, PetRepository, QrTokenPort } from "../ports/pets.js";

function petData(body: Record<string, unknown>): PetChanges {
  objectInput(body);
  if (body.qrToken !== undefined) throw new BusinessError(422, "QR tokens are generated by the server. Use the QR rotation endpoint.");
  const data: PetChanges = {};
  if (body.name !== undefined) data.name = requiredText(body.name, "Pet name", 200);
  if (body.species !== undefined) data.species = enumValue(body.species, "species", ["dog", "cat", "rabbit", "other"]);
  if (body.gender !== undefined) data.gender = enumValue(body.gender, "gender", ["unknown", "male", "female"]);
  if (body.healthStatus !== undefined) data.healthStatus = enumValue(body.healthStatus, "health status", ["healthy", "stable", "vaccination_due", "under_treatment", "critical"]);
  for (const key of ["breed", "ageLabel", "microchipId", "notes", "identifyingMarks", "lastSeenLocation"] as const)
    if (body[key] !== undefined) data[key] = optionalText(body[key], key);
  if (body.avatarUrl !== undefined) data.avatarUrl = optionalText(body.avatarUrl, "avatarUrl", 7_000_000);
  if (body.weightKg !== undefined) data.weightKg = positiveNumber(body.weightKg, "weightKg", 999.99, false, 2);
  if (body.allergies !== undefined) {
    if (!Array.isArray(body.allergies) || body.allergies.length > 100) throw new BusinessError(422, "Allergies must be an array with at most 100 strings.");
    data.allergies = body.allergies.map(value => requiredText(value, "Allergy", 200));
  }
  if (body.qrEnabled !== undefined) data.qrEnabled = booleanValue(body.qrEnabled, "qrEnabled");
  if (body.publicProfile !== undefined) {
    objectInput(body.publicProfile);
    for (const key of ["showOwnerPhone", "showOwnerEmail", "showOwnerAddress", "showMedicalAlerts"] as const)
      if (body.publicProfile[key] !== undefined) data[key] = booleanValue(body.publicProfile[key], key);
    if (body.publicProfile.rescueNote !== undefined) data.rescueNote = optionalText(body.publicProfile.rescueNote, "rescueNote");
  }
  return data;
}

export class PetsService {
  constructor(private readonly pets: PetRepository, private readonly qrTokens: QrTokenPort) {}

  list(actor: Actor, requestedOwnerId?: string) {
    return this.pets.list(actor.role === "owner" ? actor.sub : requestedOwnerId);
  }

  async create(actor: Actor, body: Record<string, unknown>) {
    objectInput(body);
    const data = petData(body);
    const ownerId = actor.role === "owner" ? actor.sub : requiredText(body.ownerId, "Owner", 200);
    const name = requiredText(body.name, "Pet name", 200);
    if (actor.role !== "owner" && !await this.pets.ownerExists(ownerId))
      throw new BusinessError(422, "Select an existing pet owner.");
    return this.pets.create({
      species: "other", gender: "unknown", healthStatus: "healthy", allergies: [],
      ...data, ownerId, name, qrToken: this.qrTokens.create(),
    });
  }

  private async editable(actor: Actor, id: string) {
    const pet = await this.pets.find(id);
    if (!pet) throw new BusinessError(404, "Pet not found.");
    if (actor.role === "owner" && pet.ownerId !== actor.sub) throw new BusinessError(403, "You cannot update this pet.");
    return pet;
  }

  async update(actor: Actor, id: string, body: Record<string, unknown>) {
    const data = petData(body);
    const pet = await this.editable(actor, id);
    return this.pets.update(pet.id, data);
  }

  async rotateQrToken(actor: Actor, id: string) {
    const pet = await this.editable(actor, id);
    return this.pets.update(pet.id, { qrToken: this.qrTokens.create() });
  }
}
